<?php

namespace Pi\FrontBundle\Repository;

/**
 * VeterinairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeterinairesRepository extends \Doctrine\ORM\EntityRepository
{
    //fct
}
